name       : openvpn
version    : 2.4.9
release    : 12
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.9.tar.gz : cccadc1b4849107df3ba34f5d9d64284676ba99aa88415f1bcd481e08a3bc548
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2
    - lzo-devel
setup      : |
    %reconfigure --enable-systemd \
                 --enable-iproute2
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
