name       : openvpn
version    : 2.4.0
release    : 3
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.0.tar.gz : dc8b2631331a84f2205cb7da73fd3ce496c21d5a5f180ae634cbd47fd9e4ac12
license    :
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2-devel
    - lzo-devel
setup      : |
    %reconfigure  --enable-systemd --enable-iproute2
build      : |
    %make
install    : |
    %make_install
