name       : openvpn
version    : 2.3.8
release    : 1
source     :
    - http://swupdate.openvpn.net/community/releases/openvpn-2.3.8.tar.gz : 532435eff61c14b44a583f27b72f93e7864e96c95fe51134ec0ad4b1b1107c51
license    :
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - Zlib
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2-devel
    - lzo-devel
setup      : |
    %configure  --enable-systemd --enable-iproute2
build      : |
    %make
install    : |
    %make_install
