name       : openvpn
version    : 2.4.2
release    : 6
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.2.tar.gz : f5a86964655d056a007c9de3d5ace3c9052d2114e92f8bceeba9bd31db7c2ad0
license    :
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2
    - lzo-devel
setup      : |
    %reconfigure  --enable-systemd --enable-iproute2
build      : |
    %make
install    : |
    %make_install
