name       : openvpn
version    : 2.5.3
release    : 17
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.5.3.tar.gz : 6822bef05b4652c25d3c0c5c82ad785137bcbf394d61da08c91884a25e1cd629
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
homepage   : https://openvpn.net/community/
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(lzo2)
    - python-docutils
setup      : |
    %reconfigure --enable-async-push \
                 --enable-systemd \
                 --with-crypto-library=openssl
build      : |
    %make
install    : |
    %make_install

    rm -rf $installdir/usr/share/doc
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
