name       : openvpn
version    : 2.4.6
release    : 10
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.6.tar.gz : 7d3e68f7679290fd5b358a743ed38e2a2d66e494679530d641381049a3a7bd60
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2
    - lzo-devel
setup      : |
    %reconfigure --enable-systemd \
                 --enable-iproute2
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
