name       : openvpn
version    : 2.6.6
release    : 29
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.6.6.tar.gz : 81415358b89660c9da98d9cf26fd4942fa806fa8f653529fa100a3090c8a3951
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
homepage   : https://openvpn.net/community/
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(liblz4)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libpkcs11-helper-1)
    - pkgconfig(lzo2)
    - python-docutils
setup      : |
    %reconfigure --enable-async-push \
                 --enable-pkcs11 \
                 --enable-systemd \
                 --with-crypto-library=openssl
build      : |
    %make
install    : |
    %make_install

    rm -rf $installdir/usr/share/doc
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
