name       : openvpn
version    : 2.3.12
release    : 2
source     :
    - http://swupdate.openvpn.net/community/releases/openvpn-2.3.12.tar.gz : f5d39b8c55f75b0aab943059b20571452b494146d997b12d48ce9bd753c01cff
license    :
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - Zlib
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2-devel
    - lzo-devel
setup      : |
    %configure  --enable-systemd --enable-iproute2
build      : |
    %make
install    : |
    %make_install
