name       : openvpn
version    : 2.4.7
release    : 11
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.7.tar.gz : b5965dd08044ae20c5ea58f84fd7e32e2fac2eeaa8ac0c9349931ed4d8bf2a1d
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2
    - lzo-devel
setup      : |
    %reconfigure --enable-systemd \
                 --enable-iproute2
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
