name       : openvpn
version    : 2.4.4
release    : 8
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.4.tar.gz : be4547574d6b42beb7580257d9214009d011f8210462d346fa66b0e656a79a3a
license    :
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2
    - lzo-devel
setup      : |
    %reconfigure --enable-systemd \
                 --enable-iproute2
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
