name       : openvpn
version    : 2.5.2
release    : 15
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.5.2.tar.gz : ba38b0f2a6b4e5b1a0f353afc175625fb492e479641523edd78ffebab3416cdb
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
homepage   : https://openvpn.net/community/
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - pkgconfig(liblz4)
    - pkgconfig(lzo2)
    - mbedtls-devel
    - python-docutils
setup      : |
    %reconfigure --enable-async-push \
                 --enable-systemd \
                 --with-crypto-library=mbedtls
build      : |
    %make
install    : |
    %make_install
    
    rm -rf $installdir/usr/share/doc
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
