name       : openvpn
version    : 2.4.9
release    : 14
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.9.tar.gz : cccadc1b4849107df3ba34f5d9d64284676ba99aa88415f1bcd481e08a3bc548
license    :
    - GPL-2.0-only
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - pkgconfig(lzo2)
    - iproute2
    - mbedtls-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Change-the-default-cipher-to-AES-256-GCM-for-server-.patch
    %reconfigure --enable-async-push --enable-iproute2 --enable-systemd --with-crypto-library=mbedtls
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check

    # OpenVPN self-test (crypto)
    ./src/openvpn/openvpn --genkey --secret key
    ./src/openvpn/openvpn --test-crypto --secret key
