name       : openvpn
version    : 2.4.3
release    : 7
source     :
    - https://github.com/OpenVPN/openvpn/archive/v2.4.3.tar.gz : d2d0e65ecdc5a69ddf4a34c41cd0ec4b7e5bc1806897f78df99c9c6e3133a294
license    :
    - GPL-2.0
    - BSD-4-Clause
    - OpenSSL
    - Zlib
component  : network.clients
summary    : OpenVPN Client
description: |
    An easy-to-use, robust, and highly configurable VPN (Virtual Private Network)
builddeps  :
    - iproute2
    - lzo-devel
setup      : |
    %reconfigure  --enable-systemd --enable-iproute2
build      : |
    %make
install    : |
    %make_install
